"""Generate ROCm CI asset bundles."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .report import generate_markdown_report


GENERATOR_VERSION = "phase5"


def generate_asset_bundle(analysis: dict[str, Any], output_dir: Path) -> dict[str, Any]:
    """Generate ROCm CI assets into output_dir and return a manifest."""

    output_dir.mkdir(parents=True, exist_ok=True)

    assets = {
        ".github/workflows/rocm-ci.yml": render_workflow(analysis),
        "Dockerfile.rocm": render_dockerfile(analysis),
        "tests/test_rocm_smoke.py": render_smoke_test(analysis),
        "benchmarks/benchmark_rocm.py": render_benchmark(analysis),
        "scripts/run_rocm_validation.sh": render_validation_script(analysis),
        "ROCM_CI_REPORT.md": generate_markdown_report(analysis),
        "AMD_CLOUD_VALIDATION.md": render_amd_cloud_validation_guide(analysis),
        "evidence/README.md": render_evidence_readme(analysis),
    }

    written_files: list[dict[str, Any]] = []
    for relative_path, content in assets.items():
        destination = output_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")
        written_files.append(_file_manifest(output_dir, relative_path, content))

    manifest = {
        "generator_version": GENERATOR_VERSION,
        "repo_name": analysis.get("repo_name", "repository"),
        "source": analysis.get("source", "unknown"),
        "output_dir": str(output_dir),
        "manifest_file": str((output_dir / "ASSET_MANIFEST.json").resolve()),
        "files": written_files,
        "next_steps": [
            "Review generated assets before copying them into the target repository.",
            "Add the generated files to a branch or pull request.",
            "Run scripts/run_rocm_validation.sh on AMD Developer Cloud or a self-hosted AMD GPU runner.",
            "Store the evidence directory as CI artifacts for presentation and regression tracking.",
        ],
    }

    manifest_text = json.dumps(manifest, indent=2, sort_keys=True)
    manifest_path = output_dir / "ASSET_MANIFEST.json"
    manifest_path.write_text(manifest_text + "\n", encoding="utf-8")
    return manifest


def render_workflow(analysis: dict[str, Any]) -> str:
    """Render a GitHub Actions ROCm CI workflow."""

    repo_name = analysis.get("repo_name", "repository")
    has_requirements = "requirements.txt" in analysis.get("dependencies", {}).get("by_file", {})
    install_requirements = "true" if has_requirements else "false"

    return f"""# Generated by ROCm CI Doctor for {repo_name}.
# This workflow requires a self-hosted AMD GPU runner or an AMD Developer Cloud runner.
# GitHub-hosted runners do not provide AMD Instinct GPUs.

name: ROCm CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  rocm-smoke:
    name: ROCm smoke test
    runs-on: [self-hosted, linux, x64, rocm]
    timeout-minutes: 45
    env:
      PYTHONUNBUFFERED: "1"
      ROCM_CI_INSTALL_REQUIREMENTS: "{install_requirements}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner environment
        run: |
          python --version
          which python
          rocm-smi || true
          python - <<'PY'
          import json
          try:
              import torch
              info = {{
                  "torch_version": torch.__version__,
                  "torch_hip_version": getattr(torch.version, "hip", None),
                  "cuda_api_available": torch.cuda.is_available(),
                  "device_count": torch.cuda.device_count(),
              }}
          except Exception as exc:
              info = {{"torch_import_error": repr(exc)}}
          print(json.dumps(info, indent=2, sort_keys=True))
          PY

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ "$ROCM_CI_INSTALL_REQUIREMENTS" = "true" ] && [ -f requirements.txt ]; then
            grep -Eiv '(\\+cu[0-9]+|cupy-cuda|cuda-python|nvidia-|tensorflow-gpu)' requirements.txt > /tmp/requirements-rocm.txt || true
            if [ -s /tmp/requirements-rocm.txt ]; then
              python -m pip install -r /tmp/requirements-rocm.txt
            fi
          fi
          if [ -f pyproject.toml ]; then
            python -m pip install -e . || true
          fi

      - name: Run ROCm smoke test
        run: |
          python tests/test_rocm_smoke.py

      - name: Run ROCm benchmark
        run: |
          python benchmarks/benchmark_rocm.py --json-out rocm-benchmark.json

      - name: Upload ROCm benchmark artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rocm-benchmark
          path: |
            rocm-benchmark.json
            ROCM_CI_REPORT.md
"""


def render_dockerfile(analysis: dict[str, Any]) -> str:
    """Render a ROCm-compatible Dockerfile starter."""

    repo_name = analysis.get("repo_name", "repository")
    has_requirements = "requirements.txt" in analysis.get("dependencies", {}).get("by_file", {})
    requirements_step = (
        "RUN if [ -f requirements.txt ]; then \\\n"
        "      grep -Eiv '(\\+cu[0-9]+|cupy-cuda|cuda-python|nvidia-|tensorflow-gpu)' requirements.txt > /tmp/requirements-rocm.txt || true; \\\n"
        "      if [ -s /tmp/requirements-rocm.txt ]; then python -m pip install -r /tmp/requirements-rocm.txt; fi; \\\n"
        "    fi\n"
        if has_requirements
        else ""
    )

    return f"""# Generated by ROCm CI Doctor for {repo_name}.
# Pin this image to the exact ROCm/PyTorch tag validated by your team.
ARG ROCM_PYTORCH_IMAGE=rocm/pytorch:latest
FROM ${{ROCM_PYTORCH_IMAGE}}

WORKDIR /workspace
ENV PYTHONUNBUFFERED=1

COPY . .

RUN python -m pip install --upgrade pip
{requirements_step}RUN if [ -f pyproject.toml ]; then python -m pip install -e . || true; fi

CMD ["python", "tests/test_rocm_smoke.py"]
"""


def render_smoke_test(analysis: dict[str, Any]) -> str:
    """Render a minimal PyTorch ROCm smoke test."""

    repo_name = analysis.get("repo_name", "repository")
    return f'''"""ROCm smoke test generated by ROCm CI Doctor for {repo_name}."""

from __future__ import annotations

import json
import os
import sys
import time


def main() -> int:
    try:
        import torch
    except Exception as exc:
        print(json.dumps({{"status": "error", "stage": "import_torch", "error": repr(exc)}}, indent=2))
        return 1

    allow_cpu = os.environ.get("ROCM_CI_ALLOW_CPU", "").lower() in {{"1", "true", "yes"}}
    cuda_available = torch.cuda.is_available()
    device_count = torch.cuda.device_count()
    hip_version = getattr(torch.version, "hip", None)

    if not cuda_available and not allow_cpu:
        print(
            json.dumps(
                {{
                    "status": "error",
                    "stage": "device_discovery",
                    "message": "No AMD/ROCm GPU is visible through the PyTorch CUDA API.",
                    "torch_version": torch.__version__,
                    "torch_hip_version": hip_version,
                    "device_count": device_count,
                }},
                indent=2,
                sort_keys=True,
            )
        )
        return 1

    device = torch.device("cuda" if cuda_available else "cpu")
    started = time.perf_counter()
    x = torch.randn((512, 512), device=device, dtype=torch.float32)
    y = torch.randn((512, 512), device=device, dtype=torch.float32)
    z = x @ y
    if device.type == "cuda":
        torch.cuda.synchronize()
    elapsed_ms = (time.perf_counter() - started) * 1000

    payload = {{
        "status": "ok",
        "device": str(device),
        "device_count": device_count,
        "device_name": torch.cuda.get_device_name(0) if cuda_available else "cpu",
        "torch_version": torch.__version__,
        "torch_hip_version": hip_version,
        "elapsed_ms": round(elapsed_ms, 3),
        "result_checksum": round(float(z.sum().item()), 4),
    }}
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_benchmark(analysis: dict[str, Any]) -> str:
    """Render a small ROCm benchmark script."""

    repo_name = analysis.get("repo_name", "repository")
    return f'''"""Small ROCm benchmark generated by ROCm CI Doctor for {repo_name}."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import statistics
import time


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a small PyTorch ROCm matrix benchmark.")
    parser.add_argument("--matrix-size", type=int, default=2048)
    parser.add_argument("--iterations", type=int, default=10)
    parser.add_argument("--warmup", type=int, default=3)
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--allow-cpu", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        import torch
    except Exception as exc:
        return _finish({{"status": "error", "stage": "import_torch", "error": repr(exc)}}, args.json_out)

    allow_cpu = args.allow_cpu or os.environ.get("ROCM_CI_ALLOW_CPU", "").lower() in {{"1", "true", "yes"}}
    cuda_available = torch.cuda.is_available()
    if not cuda_available and not allow_cpu:
        return _finish(
            {{
                "status": "error",
                "stage": "device_discovery",
                "message": "No AMD/ROCm GPU is visible through the PyTorch CUDA API.",
                "torch_version": torch.__version__,
                "torch_hip_version": getattr(torch.version, "hip", None),
            }},
            args.json_out,
        )

    device = torch.device("cuda" if cuda_available else "cpu")
    size = args.matrix_size
    a = torch.randn((size, size), device=device, dtype=torch.float32)
    b = torch.randn((size, size), device=device, dtype=torch.float32)

    for _ in range(args.warmup):
        _ = a @ b
    _sync(device, torch)

    times_ms = []
    for _ in range(args.iterations):
        started = time.perf_counter()
        result = a @ b
        _sync(device, torch)
        times_ms.append((time.perf_counter() - started) * 1000)

    payload = {{
        "status": "ok",
        "benchmark": "matrix_multiply",
        "matrix_size": size,
        "iterations": args.iterations,
        "device": str(device),
        "device_name": torch.cuda.get_device_name(0) if cuda_available else "cpu",
        "torch_version": torch.__version__,
        "torch_hip_version": getattr(torch.version, "hip", None),
        "mean_ms": round(statistics.fmean(times_ms), 3),
        "median_ms": round(statistics.median(times_ms), 3),
        "min_ms": round(min(times_ms), 3),
        "max_ms": round(max(times_ms), 3),
        "result_checksum": round(float(result.sum().item()), 4),
    }}
    return _finish(payload, args.json_out)


def _sync(device, torch_module) -> None:
    if device.type == "cuda":
        torch_module.cuda.synchronize()


def _finish(payload: dict, json_out: Path | None) -> int:
    text = json.dumps(payload, indent=2, sort_keys=True)
    print(text)
    if json_out:
        json_out.write_text(text + "\\n", encoding="utf-8")
    return 0 if payload.get("status") == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_validation_script(analysis: dict[str, Any]) -> str:
    """Render an AMD/ROCm validation runner for hardware evidence capture."""

    repo_name = analysis.get("repo_name", "repository")
    return f"""#!/usr/bin/env bash
# Generated by ROCm CI Doctor for {repo_name}.
# Run this on AMD Developer Cloud or a self-hosted AMD/ROCm GPU runner.

set -euo pipefail

EVIDENCE_DIR="${{1:-rocm-validation-evidence}}"
mkdir -p "$EVIDENCE_DIR"

echo "[rocm-ci-doctor] writing evidence to $EVIDENCE_DIR"

{{
  echo "# ROCm CI Doctor Validation Evidence"
  echo
  echo "- Repository: {repo_name}"
  echo "- Started UTC: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "- Hostname: $(hostname)"
  echo "- Kernel: $(uname -srmo)"
}} > "$EVIDENCE_DIR/SUMMARY.md"

python - <<'PY' > "$EVIDENCE_DIR/environment.json"
from __future__ import annotations

import json
import platform
import shutil
import subprocess


def run(command: list[str]) -> dict:
    executable = shutil.which(command[0])
    if executable is None:
        return {{"available": False, "command": command}}
    completed = subprocess.run(command, text=True, capture_output=True, check=False)
    return {{
        "available": True,
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }}


payload = {{
    "platform": platform.platform(),
    "python": platform.python_version(),
    "rocm_smi": run(["rocm-smi"]),
}}

try:
    import torch

    payload["torch"] = {{
        "version": torch.__version__,
        "hip_version": getattr(torch.version, "hip", None),
        "cuda_api_available": torch.cuda.is_available(),
        "device_count": torch.cuda.device_count(),
        "devices": [
            torch.cuda.get_device_name(index)
            for index in range(torch.cuda.device_count())
        ],
    }}
except Exception as exc:
    payload["torch_error"] = repr(exc)

print(json.dumps(payload, indent=2, sort_keys=True))
PY

echo "[rocm-ci-doctor] running smoke test"
python tests/test_rocm_smoke.py | tee "$EVIDENCE_DIR/smoke.json"

echo "[rocm-ci-doctor] running benchmark"
python benchmarks/benchmark_rocm.py --json-out "$EVIDENCE_DIR/benchmark.json" | tee "$EVIDENCE_DIR/benchmark.stdout.log"

python - <<'PY' "$EVIDENCE_DIR"
from __future__ import annotations

import json
import sys
from pathlib import Path

evidence_dir = Path(sys.argv[1])
environment = json.loads((evidence_dir / "environment.json").read_text(encoding="utf-8"))
smoke = json.loads((evidence_dir / "smoke.json").read_text(encoding="utf-8"))
benchmark = json.loads((evidence_dir / "benchmark.json").read_text(encoding="utf-8"))

torch_info = environment.get("torch", {{}})
lines = [
    "",
    "## Result",
    "",
    f"- Smoke test status: {{smoke.get('status', 'unknown')}}",
    f"- Benchmark status: {{benchmark.get('status', 'unknown')}}",
    f"- Device: {{smoke.get('device_name', 'unknown')}}",
    f"- Torch: {{torch_info.get('version', smoke.get('torch_version', 'unknown'))}}",
    f"- ROCm/HIP: {{torch_info.get('hip_version', smoke.get('torch_hip_version', 'unknown'))}}",
    f"- Benchmark mean ms: {{benchmark.get('mean_ms', 'unknown')}}",
    "",
    "Evidence files:",
    "",
    "- `environment.json`",
    "- `smoke.json`",
    "- `benchmark.json`",
    "- `benchmark.stdout.log`",
]

with (evidence_dir / "SUMMARY.md").open("a", encoding="utf-8") as handle:
    handle.write("\\n".join(lines) + "\\n")

if smoke.get("status") != "ok" or benchmark.get("status") != "ok":
    raise SystemExit("ROCm validation did not complete successfully.")
if not torch_info.get("hip_version") and not smoke.get("torch_hip_version"):
    raise SystemExit("PyTorch did not report a ROCm/HIP version; this is not AMD ROCm proof.")
PY

echo "[rocm-ci-doctor] validation complete"
echo "[rocm-ci-doctor] evidence summary: $EVIDENCE_DIR/SUMMARY.md"
"""


def render_amd_cloud_validation_guide(analysis: dict[str, Any]) -> str:
    """Render a concise AMD Developer Cloud validation guide for generated bundles."""

    repo_name = analysis.get("repo_name", "repository")
    return f"""# AMD Developer Cloud Validation Guide

Generated by ROCm CI Doctor for `{repo_name}`.

This guide is the AMD Cloud handoff. Run these commands on AMD Developer Cloud or another AMD/ROCm GPU host to produce evidence for the final demo.

## What Counts As Proof

The evidence must show all of the following:

- PyTorch imports successfully.
- `torch.version.hip` reports a ROCm/HIP version.
- `torch.cuda.is_available()` is true on the AMD ROCm environment.
- The generated smoke test returns `status: "ok"`.
- The generated benchmark returns `status: "ok"` and records timing results.

PyTorch on ROCm intentionally uses the `torch.cuda` API surface, so the key proof is the HIP version plus the AMD device name.

## One-Time Cloud Steps

1. Start an AMD Developer Cloud instance with ROCm and PyTorch available.
2. Copy this generated bundle into the target repository root.
3. Install project dependencies if needed.
4. Run the validation script:

```bash
chmod +x scripts/run_rocm_validation.sh
./scripts/run_rocm_validation.sh evidence/amd-cloud
```

The script writes:

- `evidence/amd-cloud/environment.json`
- `evidence/amd-cloud/smoke.json`
- `evidence/amd-cloud/benchmark.json`
- `evidence/amd-cloud/benchmark.stdout.log`
- `evidence/amd-cloud/SUMMARY.md`

## Optional Docker Path

If you validate inside the generated container, mount AMD GPU devices according to your cloud image policy, then run:

```bash
docker build -f Dockerfile.rocm -t rocm-ci-doctor-validation .
docker run --rm -it --device=/dev/kfd --device=/dev/dri --group-add video \\
  -v "$PWD/evidence:/workspace/evidence" \\
  rocm-ci-doctor-validation \\
  bash scripts/run_rocm_validation.sh evidence/amd-cloud
```

## Demo Backup

If live cloud access fails during judging, show:

- `evidence/amd-cloud/SUMMARY.md`
- `evidence/amd-cloud/environment.json`
- `evidence/amd-cloud/smoke.json`
- `evidence/amd-cloud/benchmark.json`

Those files are enough to prove the generated assets ran on AMD ROCm hardware.
"""


def render_evidence_readme(analysis: dict[str, Any]) -> str:
    """Render evidence directory instructions for the AMD Cloud handoff."""

    repo_name = analysis.get("repo_name", "repository")
    return f"""# ROCm Validation Evidence

This directory is reserved for AMD Developer Cloud validation output for `{repo_name}`.

Run from the repository root on an AMD/ROCm host:

```bash
chmod +x scripts/run_rocm_validation.sh
./scripts/run_rocm_validation.sh evidence/amd-cloud
```

Expected files:

- `amd-cloud/SUMMARY.md`
- `amd-cloud/environment.json`
- `amd-cloud/smoke.json`
- `amd-cloud/benchmark.json`
- `amd-cloud/benchmark.stdout.log`

Do not treat CPU dry-run output as hardware proof. Real proof must include a non-empty ROCm/HIP version and an AMD GPU device name.
"""


def _file_manifest(output_dir: Path, relative_path: str, content: str) -> dict[str, Any]:
    return {
        "path": relative_path,
        "absolute_path": str((output_dir / relative_path).resolve()),
        "bytes": len(content.encode("utf-8")),
        "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
        "preview": "\n".join(content.splitlines()[:8]),
    }
