"""Markdown report generation for ROCm CI Doctor."""

from __future__ import annotations

from typing import Any

from .scoring import SEVERITIES, assess_repository


STACK_LABELS = {
    "docker": "Dockerfile",
    "github_actions": "GitHub Actions",
    "python": "Python",
    "pytorch": "PyTorch",
    "sglang": "SGLang",
    "tests": "Python tests",
    "transformers": "Transformers",
    "vllm": "vLLM",
}


def generate_markdown_report(analysis: dict[str, Any]) -> str:
    """Generate a maintainer-facing ROCm CI readiness report."""

    assessment = analysis.get("assessment") or assess_repository(analysis)
    lines: list[str] = []

    lines.extend(
        [
            f"# ROCm CI Report: {analysis.get('repo_name', 'repository')}",
            "",
            "> Static analysis generated by ROCm CI Doctor. This is a readiness estimate, not proof of runtime correctness.",
            "",
            f"**Source:** `{analysis.get('source', 'unknown')}`",
            "",
            "## Readiness Score",
            "",
            f"**Score:** {assessment['score']}/{assessment['max_score']} - {assessment['label']}",
            "",
            assessment["summary"],
            "",
            "### Score Breakdown",
            "",
            "| Check | Points | Status | Rationale |",
            "| --- | ---: | --- | --- |",
        ]
    )

    for check in assessment["checks"]:
        lines.append(
            f"| {check['name']} | {check['awarded']}/{check['points']} | {str(check['status']).title()} | {_escape_table(check['rationale'])} |"
        )

    lines.extend(["", "## Detected Stack", ""])
    stack = analysis.get("detected_stack", {})
    for name in sorted(stack):
        status = "Yes" if stack[name] else "No"
        lines.append(f"- **{_stack_label(name)}:** {status}")

    lines.extend(["", "## Repository Signals", ""])
    files = analysis.get("files", {})
    lines.append(f"- Python files: {files.get('python_files_count', 0)}")
    lines.append(f"- Dockerfiles: {_join_or_none(files.get('dockerfiles', []))}")
    lines.append(f"- GitHub Actions workflows: {_join_or_none(files.get('workflow_files', []))}")
    lines.append(f"- Runtime entrypoints: {_join_or_none(files.get('entrypoint_files', []))}")
    lines.append(f"- README files: {_join_or_none(files.get('readme_files', []))}")

    lines.extend(["", "## CI Gaps", ""])
    ci_gaps = analysis.get("ci_gaps", [])
    if ci_gaps:
        for gap in ci_gaps:
            lines.append(f"- **{str(gap['severity']).title()}** `{gap['id']}`: {gap['message']}")
    else:
        lines.append("- No CI gaps were detected by static analysis.")

    lines.extend(["", "## Risks By Severity", ""])
    for severity in SEVERITIES:
        risks = assessment["risks_by_severity"][severity]
        lines.append(f"### {severity.title()}")
        lines.append("")
        if not risks:
            lines.append("- None detected.")
            lines.append("")
            continue
        for risk in risks:
            lines.append(f"- `{risk['id']}` ({risk['count']} finding(s)): {risk['message']}")
            lines.append(f"  - Category: {risk['fix_category']}")
            lines.append(f"  - Explanation: {risk['explanation']}")
            lines.append(f"  - Recommended fix: {risk['recommended_fix']}")
        lines.append("")

    lines.extend(["## Recommended Fix Categories", ""])
    fix_categories = assessment.get("fix_categories", [])
    if fix_categories:
        for category in fix_categories:
            risk_ids = ", ".join(f"`{risk_id}`" for risk_id in category["risk_ids"])
            lines.append(f"- **{category['category']}** ({category['count']} finding(s)): {risk_ids}")
    else:
        lines.append("- No fix categories were generated.")

    lines.extend(["", "## Recommended Generated Assets", ""])
    for asset in analysis.get("recommended_assets", []):
        lines.append(f"- `{asset['path']}`: {asset['reason']}")

    lines.extend(
        [
            "",
            "## AMD Developer Cloud Runbook",
            "",
            "1. Add the generated ROCm CI assets to a branch.",
            "2. Run the smoke test on an AMD Developer Cloud instance with ROCm and PyTorch available.",
            "3. Save the smoke test output and benchmark output as CI artifacts.",
            "4. Treat the generated score as a static signal and the AMD runtime logs as the actual compatibility proof.",
            "",
            "Suggested validation commands after generating the bundle:",
            "",
            "```bash",
            "python tests/test_rocm_smoke.py",
            "python benchmarks/benchmark_rocm.py",
            "```",
            "",
        ]
    )

    return "\n".join(lines)


def _join_or_none(values: list[str]) -> str:
    if not values:
        return "none"
    return ", ".join(f"`{value}`" for value in values)


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _stack_label(name: str) -> str:
    return STACK_LABELS.get(name, name.replace("_", " ").title())
